src/LogViewer/Controllers/LogViewerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlertSense.Lumberjack.Contracts.Entities;
using AlertSense.Lumberjack.Contracts.Managers;
using AlertSense.Lumberjack.Services.LogService;
using log4net;
using LogViewer.Models;

namespace LogViewer.Controllers
{
    public class LogViewerController : Controller
    {
        private ILogViewerManager _logViewerManager;
        public ILogViewerManager LogViewerManager
        {
            get
            {
                return _logViewerManager ?? (_logViewerManager = LogViewerManagerFactory.CreateManager());
            }
            set { _logViewerManager = value; }
        }

        public ActionResult Index()
        {
            ILog log = LogManager.GetLogger(typeof(LogViewerController));
            log.Debug("Loading LogViewer Controller.");

            var logs = LogViewerManager.GetAllLogs();
            return View(logs);
        }

    }
}

src/LogViewer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - The Viewer of the Logs</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Lumberjack", "Index", "LogViewer")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("LogViewer", "Index", "LogViewer")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Lumberjack Log Viewer</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>